schema = 3

[mod]
  [mod."github.com/PuerkitoBio/goquery"]
    version = "v1.8.1"
    hash = "sha256-z2RaB8PVPEzSJdMUfkfNjT616yXWTjW2gkhNOh989ZU="
  [mod."github.com/a-h/htmlformat"]
    version = "v0.0.0-20231108124658-5bd994fe268e"
    hash = "sha256-YSl9GsXhc0L2oKGZLwwjUtpe5W6ra6kk74zvQdsDCMU="
  [mod."github.com/a-h/parse"]
    version = "v0.0.0-20240121214402-3caf7543159a"
    hash = "sha256-ee/g6xwwhtF7vVt3griUSh96Kz4z0hM5/tpXxHW6PZk="
  [mod."github.com/a-h/pathvars"]
    version = "v0.0.14"
    hash = "sha256-2NytUpcO0zbzE5XunCLcK3jDqxYzmyb3WqtYDEudAYg="
  [mod."github.com/a-h/protocol"]
    version = "v0.0.0-20240704131721-1e461c188041"
    hash = "sha256-KSw8m+kVIubEi+nuS3dMdBw2ZZTlmcKD/hGbVRFaE5Q="
  [mod."github.com/andybalholm/brotli"]
    version = "v1.1.0"
    hash = "sha256-njLViV4v++ZdgOWGWzlvkefuFvA/nkugl3Ta/h1nu/0="
  [mod."github.com/andybalholm/cascadia"]
    version = "v1.3.1"
    hash = "sha256-M0u22DXSeXUaYtl1KoW1qWL46niFpycFkraCEQ/luYA="
  [mod."github.com/cenkalti/backoff/v4"]
    version = "v4.3.0"
    hash = "sha256-wfVjNZsGG1WoNC5aL+kdcy6QXPgZo4THAevZ1787md8="
  [mod."github.com/cli/browser"]
    version = "v1.3.0"
    hash = "sha256-06hcvQeOEm31clxkTuZ8ts8ZtdNKY575EsM1osRVpLg="
  [mod."github.com/fatih/color"]
    version = "v1.16.0"
    hash = "sha256-Aq/SM28aPJVzvapllQ64R/DM4aZ5CHPewcm/AUJPyJQ="
  [mod."github.com/fsnotify/fsnotify"]
    version = "v1.7.0"
    hash = "sha256-MdT2rQyQHspPJcx6n9ozkLbsktIOJutOqDuKpNAtoZY="
  [mod."github.com/google/go-cmp"]
    version = "v0.6.0"
    hash = "sha256-qgra5jze4iPGP0JSTVeY5qV5AvEnEu39LYAuUCIkMtg="
  [mod."github.com/mattn/go-colorable"]
    version = "v0.1.13"
    hash = "sha256-qb3Qbo0CELGRIzvw7NVM1g/aayaz4Tguppk9MD2/OI8="
  [mod."github.com/mattn/go-isatty"]
    version = "v0.0.20"
    hash = "sha256-qhw9hWtU5wnyFyuMbKx+7RB8ckQaFQ8D+8GKPkN3HHQ="
  [mod."github.com/natefinch/atomic"]
    version = "v1.0.1"
    hash = "sha256-fbOVHCwRNI8PFjC4o0YXpKZO0JU2aWTfH5c7WXXKMHg="
  [mod."github.com/rs/cors"]
    version = "v1.11.0"
    hash = "sha256-hF25bVehtWCQsxiOfLuL4Hv8NKVunEqLPk/Vcuheha0="
  [mod."github.com/segmentio/asm"]
    version = "v1.2.0"
    hash = "sha256-zbNuKxNrUDUc6IlmRQNuJQzVe5Ol/mqp7srDg9IMMqs="
  [mod."github.com/segmentio/encoding"]
    version = "v0.4.0"
    hash = "sha256-4pWI9eTZRRDP9kO8rG6vbLCtBVVRLtbCJKd0Z2+8JoU="
  [mod."github.com/stretchr/testify"]
    version = "v1.8.4"
    hash = "sha256-MoOmRzbz9QgiJ+OOBo5h5/LbilhJfRUryvzHJmXAWjo="
  [mod."go.lsp.dev/jsonrpc2"]
    version = "v0.10.0"
    hash = "sha256-RbRsMYVBLR7ZDHHGMooycrkdbIauMXkQjVOGP7ggSgM="
  [mod."go.lsp.dev/pkg"]
    version = "v0.0.0-20210717090340-384b27a52fb2"
    hash = "sha256-TxS0Iqe1wbIaFe7MWZJRQdgqhKE8i8CggaGSV9zU1Vg="
  [mod."go.lsp.dev/uri"]
    version = "v0.3.0"
    hash = "sha256-jGP0N7Gf+bql5oJraUo33sXqWg7AKOTj0D8b4paV4dc="
  [mod."go.uber.org/multierr"]
    version = "v1.11.0"
    hash = "sha256-Lb6rHHfR62Ozg2j2JZy3MKOMKdsfzd1IYTR57r3Mhp0="
  [mod."go.uber.org/zap"]
    version = "v1.27.0"
    hash = "sha256-8655KDrulc4Das3VRduO9MjCn8ZYD5WkULjCvruaYsU="
  [mod."golang.org/x/mod"]
    version = "v0.20.0"
    hash = "sha256-nXYnY2kpbVkaZ/7Mf7FmxwGDX7N4cID3gKjGghmVRp4="
  [mod."golang.org/x/net"]
    version = "v0.28.0"
    hash = "sha256-WdH/mgsX/CB+CiYtXEwJAXHN8FgtW2YhFcWwrrHNBLo="
  [mod."golang.org/x/sync"]
    version = "v0.8.0"
    hash = "sha256-usvF0z7gq1vsX58p4orX+8WHlv52pdXgaueXlwj2Wss="
  [mod."golang.org/x/sys"]
    version = "v0.23.0"
    hash = "sha256-tC6QVLu72bADgINz26FUGdmYqKgsU45bHPg7sa0ZV7w="
  [mod."golang.org/x/tools"]
    version = "v0.24.0"
    hash = "sha256-2LBEW//aW8qrHc26F6Ma7CsYJRaCALfi0xQl2KgWems="
